package com.roastos.app

import org.json.JSONArray
import org.json.JSONObject
import java.io.OutputStreamWriter
import java.net.HttpURLConnection
import java.net.URL

class OpenAiProvider : RoastAiProvider {

    override val type: RoastAiProviderType = RoastAiProviderType.REMOTE_API

    override fun generate(
        request: RoastAiRequest,
        config: RoastAiServiceConfig
    ): RoastAiServiceResult {

        if (config.apiBaseUrl.isBlank()) {
            return RoastAiServiceResult(
                success = false,
                providerType = type,
                response = null,
                errorMessage = "API base url not configured"
            )
        }

        try {

            val prompt = buildPrompt(request)

            val payload = JSONObject()
            payload.put("model", config.modelName)

            val messages = JSONArray()

            val systemMsg = JSONObject()
            systemMsg.put("role", "system")
            systemMsg.put("content", request.systemInstruction)
            messages.put(systemMsg)

            val userMsg = JSONObject()
            userMsg.put("role", "user")
            userMsg.put("content", prompt)
            messages.put(userMsg)

            payload.put("messages", messages)

            val url = URL(config.apiBaseUrl)

            val conn = url.openConnection() as HttpURLConnection
            conn.requestMethod = "POST"
            conn.setRequestProperty("Content-Type", "application/json")

            if (config.apiKeyHint.isNotBlank()) {
                conn.setRequestProperty(
                    "Authorization",
                    "Bearer ${config.apiKeyHint}"
                )
            }

            conn.doOutput = true

            val writer = OutputStreamWriter(conn.outputStream)
            writer.write(payload.toString())
            writer.flush()
            writer.close()

            val responseCode = conn.responseCode

            if (responseCode != 200) {

                return RoastAiServiceResult(
                    success = false,
                    providerType = type,
                    response = null,
                    errorMessage = "HTTP $responseCode"
                )
            }

            val responseText = conn.inputStream
                .bufferedReader()
                .use { it.readText() }

            val json = JSONObject(responseText)

            val content =
                json.getJSONArray("choices")
                    .getJSONObject(0)
                    .getJSONObject("message")
                    .getString("content")

            val aiResponse = RoastAiResponses.textExplanation(
                text = content,
                reasoning = "Generated by OpenAI provider"
            )

            return RoastAiServiceResult(
                success = true,
                providerType = type,
                response = aiResponse,
                rawPayload = responseText
            )

        } catch (e: Exception) {

            return RoastAiServiceResult(
                success = false,
                providerType = type,
                response = null,
                errorMessage = e.message ?: "Unknown error"
            )
        }
    }

    private fun buildPrompt(
        request: RoastAiRequest
    ): String {

        if (request.userMessageOverride.isNotBlank()) {
            return request.userMessageOverride
        }

        return buildString {

            appendLine("Roast OS Context")
            appendLine("----------------")
            appendLine(request.context.compactPromptBlock())
            appendLine()

            appendLine("Task")
            appendLine(request.context.intent.name)
        }
    }
}
